/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mkononen' at '24/10/16 2:30 PM' with Gradle 2.10
 *
 * @author mkononen, @date 24/10/16 2:30 PM
 */
package controller.library;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
