import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mkononen' at '24/10/16 2:30 PM' with Gradle 2.10
 *
 * @author mkononen, @date 24/10/16 2:30 PM
 */
public class LibraryTest {
    @Test public void TestBasicAssertion() {
        assertTrue(1 == 1);
    }
}
